language: elixir
elixir:
  - '1.8.1'
otp_release: '21'

matrix:
  include:
    - elixir: '1.7.4'
      otp_release: '21'
    - elixir: '1.7.2'
      otp_release: '21'
    - elixir: '1.7.4'
      otp_release: '20'
    - elixir: '1.7.2'
      otp_release: '20'
